# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import examlytics_pb2 as examlytics__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in examlytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExamlyticsAIStub(object):
    """Improved service definition for better maintainability
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateExam = channel.unary_unary(
                '/examlytics.v1.ExamlyticsAI/GenerateExam',
                request_serializer=examlytics__pb2.GenerateExamRequest.SerializeToString,
                response_deserializer=examlytics__pb2.GenerateExamResponse.FromString,
                _registered_method=True)
        self.AnalyzeExam = channel.unary_unary(
                '/examlytics.v1.ExamlyticsAI/AnalyzeExam',
                request_serializer=examlytics__pb2.AnalyzeExamRequest.SerializeToString,
                response_deserializer=examlytics__pb2.AnalyzeExamResponse.FromString,
                _registered_method=True)
        self.StreamExplanation = channel.unary_stream(
                '/examlytics.v1.ExamlyticsAI/StreamExplanation',
                request_serializer=examlytics__pb2.ExplanationRequest.SerializeToString,
                response_deserializer=examlytics__pb2.ExplanationResponse.FromString,
                _registered_method=True)
        self.PredictPerformance = channel.unary_unary(
                '/examlytics.v1.ExamlyticsAI/PredictPerformance',
                request_serializer=examlytics__pb2.PredictPerformanceRequest.SerializeToString,
                response_deserializer=examlytics__pb2.PredictPerformanceResponse.FromString,
                _registered_method=True)


class ExamlyticsAIServicer(object):
    """Improved service definition for better maintainability
    """

    def GenerateExam(self, request, context):
        """Generates a new exam based on user criteria
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeExam(self, request, context):
        """Analyzes a submitted exam and provides detailed feedback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExplanation(self, request, context):
        """Streamed explanation generation for better UX
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictPerformance(self, request, context):
        """Predicts user performance based on history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExamlyticsAIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateExam': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateExam,
                    request_deserializer=examlytics__pb2.GenerateExamRequest.FromString,
                    response_serializer=examlytics__pb2.GenerateExamResponse.SerializeToString,
            ),
            'AnalyzeExam': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeExam,
                    request_deserializer=examlytics__pb2.AnalyzeExamRequest.FromString,
                    response_serializer=examlytics__pb2.AnalyzeExamResponse.SerializeToString,
            ),
            'StreamExplanation': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExplanation,
                    request_deserializer=examlytics__pb2.ExplanationRequest.FromString,
                    response_serializer=examlytics__pb2.ExplanationResponse.SerializeToString,
            ),
            'PredictPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPerformance,
                    request_deserializer=examlytics__pb2.PredictPerformanceRequest.FromString,
                    response_serializer=examlytics__pb2.PredictPerformanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'examlytics.v1.ExamlyticsAI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('examlytics.v1.ExamlyticsAI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExamlyticsAI(object):
    """Improved service definition for better maintainability
    """

    @staticmethod
    def GenerateExam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examlytics.v1.ExamlyticsAI/GenerateExam',
            examlytics__pb2.GenerateExamRequest.SerializeToString,
            examlytics__pb2.GenerateExamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeExam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examlytics.v1.ExamlyticsAI/AnalyzeExam',
            examlytics__pb2.AnalyzeExamRequest.SerializeToString,
            examlytics__pb2.AnalyzeExamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/examlytics.v1.ExamlyticsAI/StreamExplanation',
            examlytics__pb2.ExplanationRequest.SerializeToString,
            examlytics__pb2.ExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examlytics.v1.ExamlyticsAI/PredictPerformance',
            examlytics__pb2.PredictPerformanceRequest.SerializeToString,
            examlytics__pb2.PredictPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
