// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: examlytics/v1/examlytics.proto

package examlyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DifficultyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Easy          int32                  `protobuf:"varint,1,opt,name=easy,proto3" json:"easy,omitempty"`
	Medium        int32                  `protobuf:"varint,2,opt,name=medium,proto3" json:"medium,omitempty"`
	Hard          int32                  `protobuf:"varint,3,opt,name=hard,proto3" json:"hard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifficultyConfig) Reset() {
	*x = DifficultyConfig{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifficultyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifficultyConfig) ProtoMessage() {}

func (x *DifficultyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifficultyConfig.ProtoReflect.Descriptor instead.
func (*DifficultyConfig) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{0}
}

func (x *DifficultyConfig) GetEasy() int32 {
	if x != nil {
		return x.Easy
	}
	return 0
}

func (x *DifficultyConfig) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *DifficultyConfig) GetHard() int32 {
	if x != nil {
		return x.Hard
	}
	return 0
}

type GenerateExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExamType      string                 `protobuf:"bytes,2,opt,name=exam_type,json=examType,proto3" json:"exam_type,omitempty"` // JOB, CODING, ACADEMIC
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`                         // MCQ, SUBJECTIVE, MIXED
	QuestionCount int32                  `protobuf:"varint,4,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	Difficulty    *DifficultyConfig      `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Topics        []string               `protobuf:"bytes,6,rep,name=topics,proto3" json:"topics,omitempty"`
	JobCategory   string                 `protobuf:"bytes,7,opt,name=job_category,json=jobCategory,proto3" json:"job_category,omitempty"`
	Subjects      []string               `protobuf:"bytes,8,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateExamRequest) Reset() {
	*x = GenerateExamRequest{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateExamRequest) ProtoMessage() {}

func (x *GenerateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateExamRequest.ProtoReflect.Descriptor instead.
func (*GenerateExamRequest) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateExamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateExamRequest) GetExamType() string {
	if x != nil {
		return x.ExamType
	}
	return ""
}

func (x *GenerateExamRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GenerateExamRequest) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *GenerateExamRequest) GetDifficulty() *DifficultyConfig {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *GenerateExamRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *GenerateExamRequest) GetJobCategory() string {
	if x != nil {
		return x.JobCategory
	}
	return ""
}

func (x *GenerateExamRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type QuestionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // MCQ, CODING
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Topic         string                 `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	CorrectAnswer string                 `protobuf:"bytes,7,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"` // Only for backend use, maybe redundant if handled by AI
	Explanation   string                 `protobuf:"bytes,8,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionItem) Reset() {
	*x = QuestionItem{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionItem) ProtoMessage() {}

func (x *QuestionItem) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionItem.ProtoReflect.Descriptor instead.
func (*QuestionItem) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{2}
}

func (x *QuestionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionItem) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuestionItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuestionItem) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *QuestionItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QuestionItem) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *QuestionItem) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type GenerateExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        string                 `protobuf:"bytes,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	Questions     []*QuestionItem        `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	TimeLimit     int32                  `protobuf:"varint,3,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateExamResponse) Reset() {
	*x = GenerateExamResponse{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateExamResponse) ProtoMessage() {}

func (x *GenerateExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateExamResponse.ProtoReflect.Descriptor instead.
func (*GenerateExamResponse) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateExamResponse) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *GenerateExamResponse) GetQuestions() []*QuestionItem {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GenerateExamResponse) GetTimeLimit() int32 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

type ResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	TimeSpent     int32                  `protobuf:"varint,3,opt,name=time_spent,json=timeSpent,proto3" json:"time_spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseItem) Reset() {
	*x = ResponseItem{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseItem) ProtoMessage() {}

func (x *ResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseItem.ProtoReflect.Descriptor instead.
func (*ResponseItem) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseItem) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *ResponseItem) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ResponseItem) GetTimeSpent() int32 {
	if x != nil {
		return x.TimeSpent
	}
	return 0
}

type AnalyzeExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        string                 `protobuf:"bytes,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Responses     []*ResponseItem        `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeExamRequest) Reset() {
	*x = AnalyzeExamRequest{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeExamRequest) ProtoMessage() {}

func (x *AnalyzeExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeExamRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeExamRequest) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeExamRequest) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *AnalyzeExamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeExamRequest) GetResponses() []*ResponseItem {
	if x != nil {
		return x.Responses
	}
	return nil
}

type TopicAnalysisItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // WEAK, STRONG, AVERAGE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicAnalysisItem) Reset() {
	*x = TopicAnalysisItem{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicAnalysisItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicAnalysisItem) ProtoMessage() {}

func (x *TopicAnalysisItem) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicAnalysisItem.ProtoReflect.Descriptor instead.
func (*TopicAnalysisItem) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{6}
}

func (x *TopicAnalysisItem) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *TopicAnalysisItem) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *TopicAnalysisItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ImprovementItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	PracticeDays  int32                  `protobuf:"varint,3,opt,name=practice_days,json=practiceDays,proto3" json:"practice_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImprovementItem) Reset() {
	*x = ImprovementItem{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprovementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprovementItem) ProtoMessage() {}

func (x *ImprovementItem) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprovementItem.ProtoReflect.Descriptor instead.
func (*ImprovementItem) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{7}
}

func (x *ImprovementItem) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ImprovementItem) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ImprovementItem) GetPracticeDays() int32 {
	if x != nil {
		return x.PracticeDays
	}
	return 0
}

type AnalyzeExamResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Score               float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Accuracy            float64                `protobuf:"fixed64,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	EstimatedPercentile float64                `protobuf:"fixed64,3,opt,name=estimated_percentile,json=estimatedPercentile,proto3" json:"estimated_percentile,omitempty"`
	TopicAnalysis       []*TopicAnalysisItem   `protobuf:"bytes,4,rep,name=topic_analysis,json=topicAnalysis,proto3" json:"topic_analysis,omitempty"`
	WeakTopics          []string               `protobuf:"bytes,5,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	ImprovementPlan     []*ImprovementItem     `protobuf:"bytes,6,rep,name=improvement_plan,json=improvementPlan,proto3" json:"improvement_plan,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalyzeExamResponse) Reset() {
	*x = AnalyzeExamResponse{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeExamResponse) ProtoMessage() {}

func (x *AnalyzeExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeExamResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeExamResponse) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeExamResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnalyzeExamResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *AnalyzeExamResponse) GetEstimatedPercentile() float64 {
	if x != nil {
		return x.EstimatedPercentile
	}
	return 0
}

func (x *AnalyzeExamResponse) GetTopicAnalysis() []*TopicAnalysisItem {
	if x != nil {
		return x.TopicAnalysis
	}
	return nil
}

func (x *AnalyzeExamResponse) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

func (x *AnalyzeExamResponse) GetImprovementPlan() []*ImprovementItem {
	if x != nil {
		return x.ImprovementPlan
	}
	return nil
}

type ExplanationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserAnswer    string                 `protobuf:"bytes,2,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplanationRequest) Reset() {
	*x = ExplanationRequest{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplanationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplanationRequest) ProtoMessage() {}

func (x *ExplanationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplanationRequest.ProtoReflect.Descriptor instead.
func (*ExplanationRequest) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{9}
}

func (x *ExplanationRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *ExplanationRequest) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

func (x *ExplanationRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type ExplanationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplanationResponse) Reset() {
	*x = ExplanationResponse{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplanationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplanationResponse) ProtoMessage() {}

func (x *ExplanationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplanationResponse.ProtoReflect.Descriptor instead.
func (*ExplanationResponse) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{10}
}

func (x *ExplanationResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

type PredictPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetExam    string                 `protobuf:"bytes,2,opt,name=target_exam,json=targetExam,proto3" json:"target_exam,omitempty"` // e.g., "JEE Advanced"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictPerformanceRequest) Reset() {
	*x = PredictPerformanceRequest{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictPerformanceRequest) ProtoMessage() {}

func (x *PredictPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictPerformanceRequest.ProtoReflect.Descriptor instead.
func (*PredictPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{11}
}

func (x *PredictPerformanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PredictPerformanceRequest) GetTargetExam() string {
	if x != nil {
		return x.TargetExam
	}
	return ""
}

type PredictPerformanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PredictedScore  float64                `protobuf:"fixed64,1,opt,name=predicted_score,json=predictedScore,proto3" json:"predicted_score,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // 0.0 to 1.0
	RiskLevel       string                 `protobuf:"bytes,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`                     // LOW, MODERATE, HIGH
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictPerformanceResponse) Reset() {
	*x = PredictPerformanceResponse{}
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictPerformanceResponse) ProtoMessage() {}

func (x *PredictPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examlytics_v1_examlytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictPerformanceResponse.ProtoReflect.Descriptor instead.
func (*PredictPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_examlytics_v1_examlytics_proto_rawDescGZIP(), []int{12}
}

func (x *PredictPerformanceResponse) GetPredictedScore() float64 {
	if x != nil {
		return x.PredictedScore
	}
	return 0
}

func (x *PredictPerformanceResponse) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *PredictPerformanceResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

var File_examlytics_v1_examlytics_proto protoreflect.FileDescriptor

const file_examlytics_v1_examlytics_proto_rawDesc = "" +
	"\n" +
	"\x1eexamlytics/v1/examlytics.proto\x12\rexamlytics.v1\"R\n" +
	"\x10DifficultyConfig\x12\x12\n" +
	"\x04easy\x18\x01 \x01(\x05R\x04easy\x12\x16\n" +
	"\x06medium\x18\x02 \x01(\x05R\x06medium\x12\x12\n" +
	"\x04hard\x18\x03 \x01(\x05R\x04hard\"\x9e\x02\n" +
	"\x13GenerateExamRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\texam_type\x18\x02 \x01(\tR\bexamType\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12%\n" +
	"\x0equestion_count\x18\x04 \x01(\x05R\rquestionCount\x12?\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\v2\x1f.examlytics.v1.DifficultyConfigR\n" +
	"difficulty\x12\x16\n" +
	"\x06topics\x18\x06 \x03(\tR\x06topics\x12!\n" +
	"\fjob_category\x18\a \x01(\tR\vjobCategory\x12\x1a\n" +
	"\bsubjects\x18\b \x03(\tR\bsubjects\"\xdf\x01\n" +
	"\fQuestionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05topic\x18\x06 \x01(\tR\x05topic\x12%\n" +
	"\x0ecorrect_answer\x18\a \x01(\tR\rcorrectAnswer\x12 \n" +
	"\vexplanation\x18\b \x01(\tR\vexplanation\"\x89\x01\n" +
	"\x14GenerateExamResponse\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\tR\x06examId\x129\n" +
	"\tquestions\x18\x02 \x03(\v2\x1b.examlytics.v1.QuestionItemR\tquestions\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x03 \x01(\x05R\ttimeLimit\"f\n" +
	"\fResponseItem\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"time_spent\x18\x03 \x01(\x05R\ttimeSpent\"\x81\x01\n" +
	"\x12AnalyzeExamRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\tR\x06examId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\tresponses\x18\x03 \x03(\v2\x1b.examlytics.v1.ResponseItemR\tresponses\"f\n" +
	"\x11TopicAnalysisItem\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x1a\n" +
	"\baccuracy\x18\x02 \x01(\x01R\baccuracy\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"q\n" +
	"\x0fImprovementItem\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12#\n" +
	"\rpractice_days\x18\x03 \x01(\x05R\fpracticeDays\"\xaf\x02\n" +
	"\x13AnalyzeExamResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x1a\n" +
	"\baccuracy\x18\x02 \x01(\x01R\baccuracy\x121\n" +
	"\x14estimated_percentile\x18\x03 \x01(\x01R\x13estimatedPercentile\x12G\n" +
	"\x0etopic_analysis\x18\x04 \x03(\v2 .examlytics.v1.TopicAnalysisItemR\rtopicAnalysis\x12\x1f\n" +
	"\vweak_topics\x18\x05 \x03(\tR\n" +
	"weakTopics\x12I\n" +
	"\x10improvement_plan\x18\x06 \x03(\v2\x1e.examlytics.v1.ImprovementItemR\x0fimprovementPlan\"p\n" +
	"\x12ExplanationRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1f\n" +
	"\vuser_answer\x18\x02 \x01(\tR\n" +
	"userAnswer\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"+\n" +
	"\x13ExplanationResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\"U\n" +
	"\x19PredictPerformanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtarget_exam\x18\x02 \x01(\tR\n" +
	"targetExam\"\x8f\x01\n" +
	"\x1aPredictPerformanceResponse\x12'\n" +
	"\x0fpredicted_score\x18\x01 \x01(\x01R\x0epredictedScore\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x01R\x0fconfidenceScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\tR\triskLevel2\x86\x03\n" +
	"\fExamlyticsAI\x12W\n" +
	"\fGenerateExam\x12\".examlytics.v1.GenerateExamRequest\x1a#.examlytics.v1.GenerateExamResponse\x12T\n" +
	"\vAnalyzeExam\x12!.examlytics.v1.AnalyzeExamRequest\x1a\".examlytics.v1.AnalyzeExamResponse\x12\\\n" +
	"\x11StreamExplanation\x12!.examlytics.v1.ExplanationRequest\x1a\".examlytics.v1.ExplanationResponse0\x01\x12i\n" +
	"\x12PredictPerformance\x12(.examlytics.v1.PredictPerformanceRequest\x1a).examlytics.v1.PredictPerformanceResponseBCZAgithub.com/examlytics/server/pkg/proto/examlytics/v1;examlyticsv1b\x06proto3"

var (
	file_examlytics_v1_examlytics_proto_rawDescOnce sync.Once
	file_examlytics_v1_examlytics_proto_rawDescData []byte
)

func file_examlytics_v1_examlytics_proto_rawDescGZIP() []byte {
	file_examlytics_v1_examlytics_proto_rawDescOnce.Do(func() {
		file_examlytics_v1_examlytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examlytics_v1_examlytics_proto_rawDesc), len(file_examlytics_v1_examlytics_proto_rawDesc)))
	})
	return file_examlytics_v1_examlytics_proto_rawDescData
}

var file_examlytics_v1_examlytics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_examlytics_v1_examlytics_proto_goTypes = []any{
	(*DifficultyConfig)(nil),           // 0: examlytics.v1.DifficultyConfig
	(*GenerateExamRequest)(nil),        // 1: examlytics.v1.GenerateExamRequest
	(*QuestionItem)(nil),               // 2: examlytics.v1.QuestionItem
	(*GenerateExamResponse)(nil),       // 3: examlytics.v1.GenerateExamResponse
	(*ResponseItem)(nil),               // 4: examlytics.v1.ResponseItem
	(*AnalyzeExamRequest)(nil),         // 5: examlytics.v1.AnalyzeExamRequest
	(*TopicAnalysisItem)(nil),          // 6: examlytics.v1.TopicAnalysisItem
	(*ImprovementItem)(nil),            // 7: examlytics.v1.ImprovementItem
	(*AnalyzeExamResponse)(nil),        // 8: examlytics.v1.AnalyzeExamResponse
	(*ExplanationRequest)(nil),         // 9: examlytics.v1.ExplanationRequest
	(*ExplanationResponse)(nil),        // 10: examlytics.v1.ExplanationResponse
	(*PredictPerformanceRequest)(nil),  // 11: examlytics.v1.PredictPerformanceRequest
	(*PredictPerformanceResponse)(nil), // 12: examlytics.v1.PredictPerformanceResponse
}
var file_examlytics_v1_examlytics_proto_depIdxs = []int32{
	0,  // 0: examlytics.v1.GenerateExamRequest.difficulty:type_name -> examlytics.v1.DifficultyConfig
	2,  // 1: examlytics.v1.GenerateExamResponse.questions:type_name -> examlytics.v1.QuestionItem
	4,  // 2: examlytics.v1.AnalyzeExamRequest.responses:type_name -> examlytics.v1.ResponseItem
	6,  // 3: examlytics.v1.AnalyzeExamResponse.topic_analysis:type_name -> examlytics.v1.TopicAnalysisItem
	7,  // 4: examlytics.v1.AnalyzeExamResponse.improvement_plan:type_name -> examlytics.v1.ImprovementItem
	1,  // 5: examlytics.v1.ExamlyticsAI.GenerateExam:input_type -> examlytics.v1.GenerateExamRequest
	5,  // 6: examlytics.v1.ExamlyticsAI.AnalyzeExam:input_type -> examlytics.v1.AnalyzeExamRequest
	9,  // 7: examlytics.v1.ExamlyticsAI.StreamExplanation:input_type -> examlytics.v1.ExplanationRequest
	11, // 8: examlytics.v1.ExamlyticsAI.PredictPerformance:input_type -> examlytics.v1.PredictPerformanceRequest
	3,  // 9: examlytics.v1.ExamlyticsAI.GenerateExam:output_type -> examlytics.v1.GenerateExamResponse
	8,  // 10: examlytics.v1.ExamlyticsAI.AnalyzeExam:output_type -> examlytics.v1.AnalyzeExamResponse
	10, // 11: examlytics.v1.ExamlyticsAI.StreamExplanation:output_type -> examlytics.v1.ExplanationResponse
	12, // 12: examlytics.v1.ExamlyticsAI.PredictPerformance:output_type -> examlytics.v1.PredictPerformanceResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_examlytics_v1_examlytics_proto_init() }
func file_examlytics_v1_examlytics_proto_init() {
	if File_examlytics_v1_examlytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examlytics_v1_examlytics_proto_rawDesc), len(file_examlytics_v1_examlytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examlytics_v1_examlytics_proto_goTypes,
		DependencyIndexes: file_examlytics_v1_examlytics_proto_depIdxs,
		MessageInfos:      file_examlytics_v1_examlytics_proto_msgTypes,
	}.Build()
	File_examlytics_v1_examlytics_proto = out.File
	file_examlytics_v1_examlytics_proto_goTypes = nil
	file_examlytics_v1_examlytics_proto_depIdxs = nil
}
