// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: examlytics/v1/examlytics.proto

package examlyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExamlyticsAI_GenerateExam_FullMethodName       = "/examlytics.v1.ExamlyticsAI/GenerateExam"
	ExamlyticsAI_AnalyzeExam_FullMethodName        = "/examlytics.v1.ExamlyticsAI/AnalyzeExam"
	ExamlyticsAI_StreamExplanation_FullMethodName  = "/examlytics.v1.ExamlyticsAI/StreamExplanation"
	ExamlyticsAI_PredictPerformance_FullMethodName = "/examlytics.v1.ExamlyticsAI/PredictPerformance"
)

// ExamlyticsAIClient is the client API for ExamlyticsAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Improved service definition for better maintainability
type ExamlyticsAIClient interface {
	// Generates a new exam based on user criteria
	GenerateExam(ctx context.Context, in *GenerateExamRequest, opts ...grpc.CallOption) (*GenerateExamResponse, error)
	// Analyzes a submitted exam and provides detailed feedback
	AnalyzeExam(ctx context.Context, in *AnalyzeExamRequest, opts ...grpc.CallOption) (*AnalyzeExamResponse, error)
	// Streamed explanation generation for better UX
	StreamExplanation(ctx context.Context, in *ExplanationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExplanationResponse], error)
	// Predicts user performance based on history
	PredictPerformance(ctx context.Context, in *PredictPerformanceRequest, opts ...grpc.CallOption) (*PredictPerformanceResponse, error)
}

type examlyticsAIClient struct {
	cc grpc.ClientConnInterface
}

func NewExamlyticsAIClient(cc grpc.ClientConnInterface) ExamlyticsAIClient {
	return &examlyticsAIClient{cc}
}

func (c *examlyticsAIClient) GenerateExam(ctx context.Context, in *GenerateExamRequest, opts ...grpc.CallOption) (*GenerateExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateExamResponse)
	err := c.cc.Invoke(ctx, ExamlyticsAI_GenerateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examlyticsAIClient) AnalyzeExam(ctx context.Context, in *AnalyzeExamRequest, opts ...grpc.CallOption) (*AnalyzeExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeExamResponse)
	err := c.cc.Invoke(ctx, ExamlyticsAI_AnalyzeExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examlyticsAIClient) StreamExplanation(ctx context.Context, in *ExplanationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExplanationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExamlyticsAI_ServiceDesc.Streams[0], ExamlyticsAI_StreamExplanation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExplanationRequest, ExplanationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExamlyticsAI_StreamExplanationClient = grpc.ServerStreamingClient[ExplanationResponse]

func (c *examlyticsAIClient) PredictPerformance(ctx context.Context, in *PredictPerformanceRequest, opts ...grpc.CallOption) (*PredictPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictPerformanceResponse)
	err := c.cc.Invoke(ctx, ExamlyticsAI_PredictPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamlyticsAIServer is the server API for ExamlyticsAI service.
// All implementations must embed UnimplementedExamlyticsAIServer
// for forward compatibility.
//
// Improved service definition for better maintainability
type ExamlyticsAIServer interface {
	// Generates a new exam based on user criteria
	GenerateExam(context.Context, *GenerateExamRequest) (*GenerateExamResponse, error)
	// Analyzes a submitted exam and provides detailed feedback
	AnalyzeExam(context.Context, *AnalyzeExamRequest) (*AnalyzeExamResponse, error)
	// Streamed explanation generation for better UX
	StreamExplanation(*ExplanationRequest, grpc.ServerStreamingServer[ExplanationResponse]) error
	// Predicts user performance based on history
	PredictPerformance(context.Context, *PredictPerformanceRequest) (*PredictPerformanceResponse, error)
	mustEmbedUnimplementedExamlyticsAIServer()
}

// UnimplementedExamlyticsAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamlyticsAIServer struct{}

func (UnimplementedExamlyticsAIServer) GenerateExam(context.Context, *GenerateExamRequest) (*GenerateExamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateExam not implemented")
}
func (UnimplementedExamlyticsAIServer) AnalyzeExam(context.Context, *AnalyzeExamRequest) (*AnalyzeExamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeExam not implemented")
}
func (UnimplementedExamlyticsAIServer) StreamExplanation(*ExplanationRequest, grpc.ServerStreamingServer[ExplanationResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamExplanation not implemented")
}
func (UnimplementedExamlyticsAIServer) PredictPerformance(context.Context, *PredictPerformanceRequest) (*PredictPerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictPerformance not implemented")
}
func (UnimplementedExamlyticsAIServer) mustEmbedUnimplementedExamlyticsAIServer() {}
func (UnimplementedExamlyticsAIServer) testEmbeddedByValue()                      {}

// UnsafeExamlyticsAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamlyticsAIServer will
// result in compilation errors.
type UnsafeExamlyticsAIServer interface {
	mustEmbedUnimplementedExamlyticsAIServer()
}

func RegisterExamlyticsAIServer(s grpc.ServiceRegistrar, srv ExamlyticsAIServer) {
	// If the following call panics, it indicates UnimplementedExamlyticsAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExamlyticsAI_ServiceDesc, srv)
}

func _ExamlyticsAI_GenerateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamlyticsAIServer).GenerateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamlyticsAI_GenerateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamlyticsAIServer).GenerateExam(ctx, req.(*GenerateExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamlyticsAI_AnalyzeExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamlyticsAIServer).AnalyzeExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamlyticsAI_AnalyzeExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamlyticsAIServer).AnalyzeExam(ctx, req.(*AnalyzeExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamlyticsAI_StreamExplanation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExplanationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExamlyticsAIServer).StreamExplanation(m, &grpc.GenericServerStream[ExplanationRequest, ExplanationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExamlyticsAI_StreamExplanationServer = grpc.ServerStreamingServer[ExplanationResponse]

func _ExamlyticsAI_PredictPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamlyticsAIServer).PredictPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamlyticsAI_PredictPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamlyticsAIServer).PredictPerformance(ctx, req.(*PredictPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExamlyticsAI_ServiceDesc is the grpc.ServiceDesc for ExamlyticsAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExamlyticsAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "examlytics.v1.ExamlyticsAI",
	HandlerType: (*ExamlyticsAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateExam",
			Handler:    _ExamlyticsAI_GenerateExam_Handler,
		},
		{
			MethodName: "AnalyzeExam",
			Handler:    _ExamlyticsAI_AnalyzeExam_Handler,
		},
		{
			MethodName: "PredictPerformance",
			Handler:    _ExamlyticsAI_PredictPerformance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExplanation",
			Handler:       _ExamlyticsAI_StreamExplanation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "examlytics/v1/examlytics.proto",
}
